# Datenstrom Yellow extension settings

Extension: Editrail
Version: 0.1.2
Description: A rail at the side of the window for editors.
Developer: Liam Perlaki
Tag: feature
DownloadUrl: https://github.com/pfadfinder26/yellow-editrail/archive/refs/heads/main.zip
DocumentationUrl: https://github.com/pfadfinder26/yellow-editrail
DocumentationLanguage: en, de
Published: 2026-09-28 22:53:02
Status: experimental
system/workers/editrail.php: editrail.php, create, update
system/workers/editrail.css: editrail.css, create, update
system/workers/editrail.js: editrail.js, create, update
